/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas.modul3;

/**
 *
 * @author Windows 10
 */
public class perpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ljudul = new javax.swing.JLabel();
        lpenulis = new javax.swing.JLabel();
        lpenerbit = new javax.swing.JLabel();
        ltahun = new javax.swing.JLabel();
        ldeskripsi = new javax.swing.JLabel();
        tfjudul = new javax.swing.JTextField();
        tfpenulis = new javax.swing.JTextField();
        tfpenerbit = new javax.swing.JTextField();
        tftahun = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfdeskripsi = new javax.swing.JTextArea();
        bkbibi = new javax.swing.JLabel();
        bkpelangi = new javax.swing.JLabel();
        bklayangan = new javax.swing.JLabel();
        bkhujan = new javax.swing.JLabel();
        bbibi = new javax.swing.JButton();
        bhujan = new javax.swing.JButton();
        blayangan = new javax.swing.JButton();
        bpelangi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        judul.setBackground(new java.awt.Color(0, 255, 153));
        judul.setFont(new java.awt.Font("Algerian", 3, 22)); // NOI18N
        judul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/modul3/perpus.png"))); // NOI18N
        judul.setText("PERPUSTAKAAN SEDERHANA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        ljudul.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        ljudul.setText("Judul Buku        :");

        lpenulis.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        lpenulis.setText("Penulis               :");

        lpenerbit.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        lpenerbit.setText("Penerbit             :");

        ltahun.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        ltahun.setText("Tahun Terbit   :");

        ldeskripsi.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        ldeskripsi.setText("Deskripsi          :");

        tfjudul.setEditable(false);
        tfjudul.setBackground(new java.awt.Color(0, 204, 153));
        tfjudul.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        tfjudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        tfjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfjudulActionPerformed(evt);
            }
        });

        tfpenulis.setEditable(false);
        tfpenulis.setBackground(new java.awt.Color(0, 204, 153));
        tfpenulis.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        tfpenulis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));

        tfpenerbit.setEditable(false);
        tfpenerbit.setBackground(new java.awt.Color(0, 204, 153));
        tfpenerbit.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        tfpenerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        tfpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpenerbitActionPerformed(evt);
            }
        });

        tftahun.setEditable(false);
        tftahun.setBackground(new java.awt.Color(0, 204, 153));
        tftahun.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        tftahun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        tftahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftahunActionPerformed(evt);
            }
        });

        tfdeskripsi.setEditable(false);
        tfdeskripsi.setBackground(new java.awt.Color(0, 204, 153));
        tfdeskripsi.setColumns(20);
        tfdeskripsi.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        tfdeskripsi.setRows(5);
        tfdeskripsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        jScrollPane1.setViewportView(tfdeskripsi);

        bkbibi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/modul3/bibi.jpeg"))); // NOI18N

        bkpelangi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/modul3/pelangi.jpeg"))); // NOI18N

        bklayangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/modul3/layangan.jpeg"))); // NOI18N

        bkhujan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/modul3/hujan.jpeg"))); // NOI18N

        bbibi.setText("Detail");
        bbibi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbibiActionPerformed(evt);
            }
        });

        bhujan.setText("Detail");
        bhujan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhujanActionPerformed(evt);
            }
        });

        blayangan.setText("Detail");
        blayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blayanganActionPerformed(evt);
            }
        });

        bpelangi.setText("Detail");
        bpelangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpelangiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltahun)
                    .addComponent(lpenerbit)
                    .addComponent(ljudul)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ldeskripsi)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bbibi))
                            .addComponent(bkbibi)))
                    .addComponent(lpenulis, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftahun, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bkhujan)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bhujan)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bklayangan)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(blayangan)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bpelangi))
                            .addComponent(bkpelangi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ljudul)
                                    .addComponent(tfjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lpenulis)
                                .addGap(6, 6, 6))
                            .addComponent(tfpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lpenerbit)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ldeskripsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bkbibi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftahun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltahun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bklayangan)
                            .addComponent(bkhujan)
                            .addComponent(bkpelangi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bhujan)
                        .addComponent(bbibi))
                    .addComponent(blayangan)
                    .addComponent(bpelangi))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfjudulActionPerformed

    private void tfpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpenerbitActionPerformed

    private void tftahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftahunActionPerformed

    private void bbibiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbibiActionPerformed
        tfjudul.setText(" Bibi Gill");
        tfpenulis.setText(" Tere Liye");
        tfpenerbit.setText(" Gramedia Pustaka Utama");
        tftahun.setText(" 21 Februari 2022");
        tfdeskripsi.setText(" Novel Bibi Gill adalah novel ke-12 dari novel Tere Liye yang berjudul Bumi. Seperti dalam \n "
                + "judulnya, novel ini tidak memberi tahu kelanjutan dari petualangan Raib, Seli m dan Ali, tetapi \n "
                + "untuk melengkapi kisah latar belakang Bibi Gill. Jika kamu sudah membaca serial sebelumnya \n "
                + "hingga tuntas pasti tahu bahwa Bibi Gill adalah salah satu pengajar dari Akademi Bayangan Tingkat \n "
                + "Tinggi (ABTT) yang mengajar mata kuliah Malam dan Misterinya. \n");
    }//GEN-LAST:event_bbibiActionPerformed

    private void bhujanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhujanActionPerformed
        tfjudul.setText(" Hujan");
        tfpenulis.setText(" Tere Liye");
        tfpenerbit.setText(" Gramedia Pustaka Utama");
        tftahun.setText(" Januari 2016");
        tfdeskripsi.setText(" Novel ini mengisahkan percintaan dan perjuangan hidup seorang perempuan \n "
                + "bernama Lail. Ketika Lail baru berusia 13 tahun, dirinya harus menjadi seorang anak \n "
                + "yatim piatu. Di hari pertama ia sekolah, ada sebuah bencana gunung meletus dan \n "
                + "gempa dahsyat sehingga menghancurkan kota di mana ia menetap, bahkan \n "
                + "merenggut nyawa ibu serta ayah Lail.");
    }//GEN-LAST:event_bhujanActionPerformed

    private void blayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blayanganActionPerformed
        tfjudul.setText(" Layangan Putus");
        tfpenulis.setText(" Mommy ASF");
        tfpenerbit.setText(" RDM Publisher");
        tftahun.setText(" 2020");
        tfdeskripsi.setText(" Layangan Putus mengisahkan rumah tangga Aris (dalam serial diperankan oleh \n "
                + "Reza Rahadian) bersama Kinan (Putri Marino) yang tiba-tiba diterpa masalah \n "
                + "orang ketiga, disaat rumah tangga mereka sebelumnya sangat harmonis.");
    }//GEN-LAST:event_blayanganActionPerformed

    private void bpelangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpelangiActionPerformed
        tfjudul.setText(" Laskar Pelangi");
        tfpenulis.setText(" Andrea Hirata");
        tfpenerbit.setText(" Bentang Pustaka");
        tftahun.setText(" 2005");
        tfdeskripsi.setText(" Novel Laskar Pelangi menceritakan kehidupan 10 anak yang tidak mampu, tetapi \n "
                + "memiliki semangat juang untuk melanjutkan pendidikannya di kampung Gantung, \n "
                + "Kepulauan Bangka Belitung. Sebagian besar dari kesepuluh anak yang menempuh \n "
                + "pendidikan di SD Muhammadiyah Gantung merupakan anak dari para penambang \n "
                + "timah di pulau dengan perolehan kekayaan alam timah yang terbesar di dunia.");
    }//GEN-LAST:event_bpelangiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbibi;
    private javax.swing.JButton bhujan;
    private javax.swing.JLabel bkbibi;
    private javax.swing.JLabel bkhujan;
    private javax.swing.JLabel bklayangan;
    private javax.swing.JLabel bkpelangi;
    private javax.swing.JButton blayangan;
    private javax.swing.JButton bpelangi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel ldeskripsi;
    private javax.swing.JLabel ljudul;
    private javax.swing.JLabel lpenerbit;
    private javax.swing.JLabel lpenulis;
    private javax.swing.JLabel ltahun;
    private javax.swing.JTextArea tfdeskripsi;
    private javax.swing.JTextField tfjudul;
    private javax.swing.JTextField tfpenerbit;
    private javax.swing.JTextField tfpenulis;
    private javax.swing.JTextField tftahun;
    // End of variables declaration//GEN-END:variables
}
